services:
  - type: web
    name: video-downloader-web
    env: static
    buildCommand: ""
    staticPublishPath: ./template
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
        
